### PR TITLE
Introduce Nyaplot.load_notebook

### PR DESCRIPTION
**Pull request by mrkn**
This PR introduces Nyaplot.load_notebook method to initialize Nyaplot environment on a notebook.
To introduce it, automatic initialization is removed.

JavaScript files such as `d3.min.js` are embedded inline in default.
If you want to use them on CDN, call `Nyaplot.load_notebook(:cdn)`.

### CODE REVIEW

**Comment by mrkn** [comment]
I don't think it is ready to merge currently because the following ugly message is displayed.

screenshot 2016-06-22 00 28 05

**Comment by v0dro** [comment]
One question: Naoki appears to be inactive. Do you think we should shift development to https://github.com/sciruby/nyaplot?

**Comment by mrkn** [comment]
@v0dro I'm totally with you.
I've resubmitted to sciruby/nyaplot https://github.com/SciRuby/nyaplot/pull/1

**Comment by v0dro** [comment]
Alright. Thanks.

**Pull request closed without merging**
